[package]
name = "kardamom-state"
version.workspace = true
edition.workspace = true

[dependencies]
revm.workspace = true
alloy-primitives.workspace = true
alloy-consensus.workspace = true
alloy-rpc-types-eth.workspace = true
alloy-rlp.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
libmdbx.workspace = true

[dev-dependencies]
tempfile.workspace = true
