# GENERATED by scripts/render-sequencer-job.py. Do not edit by hand.
#
# kardamom-sequencer: one job group per active tx_data lane, with 2
# racing replicas per lane (count = 2, distinct_hosts). Both replicas of
# a lane subscribe to the same per-lane tx_data multicast stream, and
# both offer refs to the Aeron Cluster, which dedups by canonical_id
# first-seen. So a replica crash costs nothing; its twin never stopped.
# See docs/agents/replicated-sequencer-shards-spec.md.
#
# Each group passes an explicit --lane and --vslots, derived from
# config/shard-map.toml (docs/specs/dynamic-sequencer-sizing.md, 3.2).
# The ports form a lane: metrics 9001 + 10 * lane, cluster egress
# 40210 + 10 * lane. Two lanes share a node without a clash.
# Placement is by Nomad, not by node meta.
#
# Note for consumers: both replicas of a lane process the same tx
# stream, so per-lane tx totals exist once per replica. Aggregate
# stream-derived counters with `max by (partition)`, never `sum`.
#
# This shares the node's Aeron media driver, through the bind-mounted
# tmpfs aeron.dir.

# Digest-pinned image. ansible/deploy.yml passes the repo:tag@sha256:...
# reference captured at push time (deploy/cluster/images.digests). Both
# replicas of every lane run the same pinned bytes. The empty default
# falls back to the mutable :dev tag in the task configs. That fallback
# is a dev affordance for manual `nomad job run` during debugging, not a
# production path.
variable "image_ref" {
  type        = string
  description = "Digest-pinned image reference (repo:tag@sha256:...) from the deploy's push manifest. Empty = mutable :dev tag fallback (dev-only)."
  default     = ""
}

variable "datacenter" {
  type        = string
  description = "The Nomad datacenter of the job. A node record is <node>.node.<datacenter>.consul."
  default     = "dc1"
}

variable "executor_count" {
  type        = number
  description = "The executor node count (node_classes.executor.count). The nonce lookups go to executor-<i>.node.<datacenter>.consul."
  default     = 3
}

job "sequencer" {
  datacenters = [var.datacenter]
  type        = "service"

  # Sequencer-role nodes only.
  constraint {
    attribute = "${meta.role}"
    value     = "sequencer"
  }

  group "seq-0" {
    # The two racing replicas of lane 0, on distinct nodes.
    count = 2
    constraint {
      operator = "distinct_hosts"
      value    = "true"
    }

    # Resilience (chaos tests): restart a crashed task on the same
    # node, and reschedule onto a healthy node on node loss. With
    # distinct_hosts, a lost replica reschedules only when a free node
    # returns. Its lane stays live the whole time, through the twin.
    restart {
      attempts = 3
      interval = "1m"
      delay    = "5s"
      mode     = "delay"
    }

    reschedule {
      delay          = "10s"
      delay_function = "exponential"
      max_delay      = "1m"
      unlimited      = true
    }

    # One replica at a time, so a config change (a resize step) never
    # takes both replicas of a lane down together.
    update {
      max_parallel     = 1
      health_check     = "task_states"
      min_healthy_time = "10s"
      healthy_deadline = "2m"
      auto_revert      = false
    }

    network {
      mode = "host"
    }

    task "sequencer-0" {
      driver = "docker"

      config {
        image = var.image_ref != "" ? var.image_ref : "registry.service.consul:5000/kardamom-sequencer:dev"
        # force_pull stays on for both paths; see the ingress job's
        # comment. The :dev fallback needs it. On the pinned path, the
        # 1.9.5 driver pulls the tag but resolves the image by digest,
        # so the pin holds.
        force_pull = true
        # Read-only rootfs. The sequencer writes only to the
        # bind-mounted aeron directory, plus Nomad's alloc, local, and
        # secrets mounts. cluster-e2e validates this.
        readonly_rootfs = true
        network_mode    = "host"
        volumes = [
          "/opt/kardamom/aeron-mount:/opt/kardamom/aeron-mount",
        ]
        args = [
          "--config", "/local/sequencer.toml",
          "--log-config", "/local/channels.toml",
          "--aeron-dir", "/opt/kardamom/aeron-mount/dir",
          # The active lane count and this lane. partition_index labels
          # the metrics; the vslot set below is the routing truth.
          "--partition-count", "2",
          "--partition-index", "0",
          "--sequencer-id", "0",
          "--lane", "0",
          "--vslots", "0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,64,66,68,70,72,74,76,78,80,82,84,86,88,90,92,94,96,98,100,102,104,106,108,110,112,114,116,118,120,122,124,126,128,130,132,134,136,138,140,142,144,146,148,150,152,154,156,158,160,162,164,166,168,170,172,174,176,178,180,182,184,186,188,190,192,194,196,198,200,202,204,206,208,210,212,214,216,218,220,222,224,226,228,230,232,234,236,238,240,242,244,246,248,250,252,254",
          # The transaction lifetime (tx_ttl_ms in group_vars/all.yml).
          "--tx-ttl-ms", "30000",
          # The executor nonce query endpoints (node_classes.executor and
          # ports.executor_nonce_query in group_vars/all.yml).
          "--executor-query-endpoints", join(",", [for i in range(var.executor_count) : "http://executor-${i}.node.${var.datacenter}.consul:9024"]),
          # This node's cluster-egress (response) endpoint, on the lane's
          # port. The node IP differs per replica, so it is injected here.
          "--cluster-egress-endpoint", "${meta.node_ip}:40210",
        ]
      }

      env {
        # Bind 0.0.0.0 so the process is scrapable off-node, on the
        # lane's metrics port. The host id names the node and the lane.
        KARDAMOM_METRICS_ADDR = "0.0.0.0:9001"
        KARDAMOM_HOST_ID      = "node${meta.node_index}-seq-0"
        # The UDP ports the discovered tx_errors publication binds, on
        # the lane's range, so two lanes can share a node.
        KARDAMOM_MDC_PORTS    = "40340-40349"
      }

      # Cluster LogConfig (Aeron streams and discovery), read through
      # --log-config.
      template {
        destination = "local/channels.toml"
        data        = file("config/channels.toml.tpl")
        # The template reads the archive records from Consul. A change
        # there re-renders the file; the process reads it once at start
        # and follows the catalog through discovery, so never restart.
        change_mode = "noop"
      }

      # This comes from one source, config/sequencer.toml.tpl. The
      # partition and lane fields in that file are placeholders,
      # overridden by the CLI flags above.
      template {
        destination = "local/sequencer.toml"
        data        = file("config/sequencer.toml.tpl")
      }

      resources {
        cpu    = 750
        memory = 512
      }
    }
  }

  group "seq-1" {
    # The two racing replicas of lane 1, on distinct nodes.
    count = 2
    constraint {
      operator = "distinct_hosts"
      value    = "true"
    }

    # Resilience (chaos tests): restart a crashed task on the same
    # node, and reschedule onto a healthy node on node loss. With
    # distinct_hosts, a lost replica reschedules only when a free node
    # returns. Its lane stays live the whole time, through the twin.
    restart {
      attempts = 3
      interval = "1m"
      delay    = "5s"
      mode     = "delay"
    }

    reschedule {
      delay          = "10s"
      delay_function = "exponential"
      max_delay      = "1m"
      unlimited      = true
    }

    # One replica at a time, so a config change (a resize step) never
    # takes both replicas of a lane down together.
    update {
      max_parallel     = 1
      health_check     = "task_states"
      min_healthy_time = "10s"
      healthy_deadline = "2m"
      auto_revert      = false
    }

    network {
      mode = "host"
    }

    task "sequencer-1" {
      driver = "docker"

      config {
        image = var.image_ref != "" ? var.image_ref : "registry.service.consul:5000/kardamom-sequencer:dev"
        # force_pull stays on for both paths; see the ingress job's
        # comment. The :dev fallback needs it. On the pinned path, the
        # 1.9.5 driver pulls the tag but resolves the image by digest,
        # so the pin holds.
        force_pull = true
        # Read-only rootfs. The sequencer writes only to the
        # bind-mounted aeron directory, plus Nomad's alloc, local, and
        # secrets mounts. cluster-e2e validates this.
        readonly_rootfs = true
        network_mode    = "host"
        volumes = [
          "/opt/kardamom/aeron-mount:/opt/kardamom/aeron-mount",
        ]
        args = [
          "--config", "/local/sequencer.toml",
          "--log-config", "/local/channels.toml",
          "--aeron-dir", "/opt/kardamom/aeron-mount/dir",
          # The active lane count and this lane. partition_index labels
          # the metrics; the vslot set below is the routing truth.
          "--partition-count", "2",
          "--partition-index", "1",
          "--sequencer-id", "1",
          "--lane", "1",
          "--vslots", "1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63,65,67,69,71,73,75,77,79,81,83,85,87,89,91,93,95,97,99,101,103,105,107,109,111,113,115,117,119,121,123,125,127,129,131,133,135,137,139,141,143,145,147,149,151,153,155,157,159,161,163,165,167,169,171,173,175,177,179,181,183,185,187,189,191,193,195,197,199,201,203,205,207,209,211,213,215,217,219,221,223,225,227,229,231,233,235,237,239,241,243,245,247,249,251,253,255",
          # The transaction lifetime (tx_ttl_ms in group_vars/all.yml).
          "--tx-ttl-ms", "30000",
          # The executor nonce query endpoints (node_classes.executor and
          # ports.executor_nonce_query in group_vars/all.yml).
          "--executor-query-endpoints", join(",", [for i in range(var.executor_count) : "http://executor-${i}.node.${var.datacenter}.consul:9024"]),
          # This node's cluster-egress (response) endpoint, on the lane's
          # port. The node IP differs per replica, so it is injected here.
          "--cluster-egress-endpoint", "${meta.node_ip}:40220",
        ]
      }

      env {
        # Bind 0.0.0.0 so the process is scrapable off-node, on the
        # lane's metrics port. The host id names the node and the lane.
        KARDAMOM_METRICS_ADDR = "0.0.0.0:9011"
        KARDAMOM_HOST_ID      = "node${meta.node_index}-seq-1"
        # The UDP ports the discovered tx_errors publication binds, on
        # the lane's range, so two lanes can share a node.
        KARDAMOM_MDC_PORTS    = "40350-40359"
      }

      # Cluster LogConfig (Aeron streams and discovery), read through
      # --log-config.
      template {
        destination = "local/channels.toml"
        data        = file("config/channels.toml.tpl")
        # The template reads the archive records from Consul. A change
        # there re-renders the file; the process reads it once at start
        # and follows the catalog through discovery, so never restart.
        change_mode = "noop"
      }

      # This comes from one source, config/sequencer.toml.tpl. The
      # partition and lane fields in that file are placeholders,
      # overridden by the CLI flags above.
      template {
        destination = "local/sequencer.toml"
        data        = file("config/sequencer.toml.tpl")
      }

      resources {
        cpu    = 750
        memory = 512
      }
    }
  }
}
