[package]
name = "kardamom-interop-feed"
version.workspace = true
edition.workspace = true

[dependencies]
kardamom-types = { workspace = true }

alloy-primitives = { workspace = true, features = ["serde"] }

jsonrpsee = { workspace = true }
serde = { workspace = true }
thiserror.workspace = true

[dev-dependencies]
serde_json = { workspace = true }
