#!/usr/bin/env bash
# =============================================================================
# ci-cluster.sh — bring up the kardamom cluster with CONTAINERS as nodes, for
# CI (.github/workflows/cluster-e2e.yml). The VM-less analogue of `make up`.
# =============================================================================
#
# ⚠ EXPERIMENTAL / NOT YET RUN GREEN. This drives the full Ansible → Nomad →
# Consul orchestration on a single host using 11 privileged systemd containers
# (Docker-in-Docker for Nomad's docker driver) on a 192.168.56.0/24 bridge with
# the contract's static IPs — so the UNMODIFIED site.yml provisions them. It is
# expected to need iteration on a real runner; the static `cluster-validate`
# workflow is the always-green gate.
#
# Prereqs (the workflow sets these up): docker + buildx on the host; the host
# docker daemon trusts 192.168.56.10:5000 as an insecure registry; ansible with
# the community.docker collection; the kardamom release binaries already built
# under target/release (BIN-per-service); the nomad CLI on PATH.
#
# Usage:  deploy/cluster/scripts/ci-cluster.sh            # up + provision + deploy + smoke
#         KEEP=1 deploy/cluster/scripts/ci-cluster.sh     # leave containers running
#
# SPLIT LAYOUT: this file is the entry point — bring-up (sysctls, bridge,
# node containers, provisioning), the stage gating (RUN_LOAD / RUN_SEMANTICS /
# RUN_CHAOS) and the ONE EXIT trap. Everything else lives in files SOURCED
# into THIS shell (they are libraries, never executed as children; only this
# file installs an EXIT trap, sourced files never do):
#   lib.sh                 control-node helpers + log/fail
#   lib-topology.sh        node-class model (nodes/IPs/ports)
#   lib-metrics.sh         fetch_metrics + prom_value (scrape/parse)
#   ci-diagnostics.sh      failure diagnostics (multicast probe, alloc dumps)
#   ci-images.sh           image build + registry push (push_image, build_*)
#   ci-stages.sh           container inventory + the env-gated stage bodies
#   validator-verdict.sh   §7c validator verdict + the divergence-log scan
#                          SHARED with chaos.sh (one implementation)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLUSTER_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
ROOT="$(cd "${CLUSTER_DIR}/../.." && pwd)"
cd "${CLUSTER_DIR}"

# Shared control-node helpers (on_control, running_alloc, all_allocs, ...)
# + log/fail — the same ones chaos.sh uses.
# shellcheck source=deploy/cluster/scripts/lib.sh
source "${SCRIPT_DIR}/lib.sh"
# Node-class model (topology_load + the executor/validator node+port mirrors).
# shellcheck source=deploy/cluster/scripts/lib-topology.sh
source "${SCRIPT_DIR}/lib-topology.sh"
# Prometheus scrape/parse helpers (fetch_metrics, prom_value).
# shellcheck source=deploy/cluster/scripts/lib-metrics.sh
source "${SCRIPT_DIR}/lib-metrics.sh"
# ci-cluster's own sourced libs (see the SPLIT LAYOUT note above).
# shellcheck source=deploy/cluster/scripts/ci-diagnostics.sh
source "${SCRIPT_DIR}/ci-diagnostics.sh"
# shellcheck source=deploy/cluster/scripts/ci-images.sh
source "${SCRIPT_DIR}/ci-images.sh"
# shellcheck source=deploy/cluster/scripts/ci-stages.sh
source "${SCRIPT_DIR}/ci-stages.sh"
# shellcheck source=deploy/cluster/scripts/validator-verdict.sh
source "${SCRIPT_DIR}/validator-verdict.sh"

NET=kardamom-net
SUBNET=192.168.56.0/24
REGISTRY=192.168.56.10:5000
TAG=dev
NODE_IMAGE=kardamom-node:ci
# NOTE: kardamom-recorder was removed (durability is now archive-at-the-sealer);
# the sealer image carries the durability sidecar.
SERVICES=(ingress sequencer executor validator da-watcher batcher)

# Node instances are GENERATED from the class model in group_vars/all.yml
# (node_classes: class -> {count, ip_start}) — the single source of truth. For
# each class we materialise `count` instances named <class>-<i>, each with a
# static IP from the class's ip_start lane on ip_prefix.0/24. Scaling a class is
# a one-line `count` change in group_vars; there is no node list / IP map / Ansible
# inventory to hand-maintain here (the inventory is generated by ci-stages.sh's
# gen_container_inventory). The regex parse (no PyYAML) lives in
# lib-topology.sh's topology_load, shared with smoke-load.sh; it populates
# NODES + NODE_IP/NODE_ROLE/NODE_TIER with `declare -g` so the
# cleanup/diagnostics traps below can read them.
topology_load \
  || { echo "ERROR: no nodes generated from node_classes" >&2; exit 1; }

cleanup() {
  [[ "${KEEP:-0}" == "1" ]] && { log "KEEP=1; leaving containers up"; return; }
  log "tearing down containers + network + docker volumes"
  for n in "${NODES[@]}"; do
    docker rm -f "kardamom-${n}" >/dev/null 2>&1 || true
    docker volume rm "kardamom-${n}-docker" "kardamom-${n}-containerd" >/dev/null 2>&1 || true
  done
  docker network rm "${NET}" >/dev/null 2>&1 || true
}

on_exit() {
  local rc="$1"
  [[ "${rc}" != "0" ]] && dump_diagnostics
  cleanup
  release_deploy_lock
}
trap 'on_exit "$?"' EXIT

# --- 0. Advisory deploy lock -------------------------------------------------
# Multiple agent sessions share this host's ONE cluster, and every deploy
# starts with a purge+wipe — two concurrent deploys destroy each other
# (2026-08-05: two sessions traded broken half-clusters for an afternoon;
# the second deploy's purge hit mid-provision containers of the first).
# The lock guards DEPLOY-vs-DEPLOY only: it is held for the duration of this
# script and released on exit (a KEEP=1 cluster left running is legitimately
# redeployable later — deploy-over-idle is how every session starts).
# A lock whose pid is dead is stale and reaped. Override (destroys the other
# deploy, on your head): KARDAMOM_CLUSTER_FORCE=1.
DEPLOY_LOCK=/tmp/kardamom-cluster-deploy.lock
release_deploy_lock() {
  # Only the holder removes it (re-check pid: a FORCE'd second deploy may
  # have replaced the file with its own pid).
  if [[ -f "${DEPLOY_LOCK}" ]]; then
    local lpid
    lpid="$(awk '{print $1; exit}' "${DEPLOY_LOCK}" 2>/dev/null)"
    [[ "${lpid}" == "$$" ]] && rm -f "${DEPLOY_LOCK}"
  fi
}
if [[ -f "${DEPLOY_LOCK}" && "${KARDAMOM_CLUSTER_FORCE:-0}" != "1" ]]; then
  read -r LOCK_PID LOCK_WHO <"${DEPLOY_LOCK}" || true
  if [[ -n "${LOCK_PID:-}" ]] && kill -0 "${LOCK_PID}" 2>/dev/null; then
    echo "ERROR: another cluster deploy is IN FLIGHT (pid ${LOCK_PID}, ${LOCK_WHO:-unknown}, ${DEPLOY_LOCK})." >&2
    echo "       Deploying now would purge its half-built cluster. Wait for it, or" >&2
    echo "       KARDAMOM_CLUSTER_FORCE=1 to override (destroys their deploy)." >&2
    exit 1
  fi
  echo "==> stale deploy lock (pid ${LOCK_PID:-?} dead); reaping"
fi
echo "$$ $(whoami)@$(hostname):${KARDAMOM_SESSION:-unlabeled} $(date -u +%FT%TZ)" >"${DEPLOY_LOCK}"
log "deploy lock acquired (${DEPLOY_LOCK}, pid $$)"

# --- 1. Host sysctls (NOT namespaced; can't be set from inside a container) --
log "applying Aeron socket-buffer sysctls on the host"
sudo sysctl -w net.core.rmem_max=16777216 net.core.wmem_max=16777216 \
                net.core.rmem_default=16777216 net.core.wmem_default=16777216

# Let bridged frames bypass iptables. With br_netfilter loaded and
# bridge-nf-call-iptables=1 (docker's default), L2-bridged IP frames traverse
# the iptables FORWARD chain — whose policy docker sets to DROP, with ACCEPT
# rules only for the traffic it recognises. Flooded UDP multicast (Aeron's
# cross-node tx_ordering + fsync/quorum watermarks) doesn't match those rules,
# so it's dropped in FORWARD even though IGMP snooping is off — unicast TCP
# (Consul/Nomad/ingress RPC) is unaffected because docker DOES allow it, which
# is exactly why the recorders log "recording initiated" but never "recording
# ready". Setting bridge-nf-call-iptables=0 makes bridged frames pure L2, so the
# bridge floods multicast between node containers unimpeded. Safe here: one
# isolated test network, no inter-network isolation to preserve.
sudo modprobe br_netfilter 2>/dev/null || true
if [[ -e /proc/sys/net/bridge/bridge-nf-call-iptables ]]; then
  sudo sysctl -w net.bridge.bridge-nf-call-iptables=0 \
                 net.bridge.bridge-nf-call-ip6tables=0 \
    && log "bridge-nf-call-iptables=0 (bridged multicast bypasses iptables)" \
    || log "WARN: could not clear bridge-nf-call-iptables"
else
  log "br_netfilter not present; bridged frames already bypass iptables"
fi

# --- 2. Bridge network with the contract subnet -----------------------------
docker network rm "${NET}" >/dev/null 2>&1 || true
log "creating bridge ${NET} (${SUBNET})"
# Name the underlying Linux bridge so its /sys path is deterministic (otherwise
# docker derives br-<network-id[:12]>). We disable IGMP snooping on it next.
BRIDGE_NAME=kardamom-br0
# Idempotent: reuse an existing ${NET} (e.g. a KEEP=1 run or local iteration) —
# recreating it would also recreate the underlying bridge and silently reset
# multicast_snooping to the kernel default (1), undoing the fix below on hosts
# where this script cannot sudo.
if ! docker network inspect "${NET}" >/dev/null 2>&1; then
  docker network create --driver bridge \
    -o "com.docker.network.bridge.name=${BRIDGE_NAME}" \
    --subnet "${SUBNET}" "${NET}"
else
  log "network ${NET} already exists; reusing"
fi

# Aeron's cross-node data plane is UDP MULTICAST (tx_ordering: sealer ->
# recorders + executor; the per-recorder fsync watermarks and the aggregated
# quorum watermark). This bridge is an isolated L2 segment with NO IGMP querier,
# so with the kernel default (multicast_snooping=1) the bridge stops flooding
# group traffic once its snooping state lapses — multicast then never crosses
# between node containers. The symptom is precise: each recorder logs "recording
# initiated" for TxOrdering but never "recording ready" (the archive's recording
# subscription gets no image), so no fsync watermark is published, the quorum
# watermark never advances, and ingress (--ack-policy on-quorum) times out with
# "timed out waiting for receipt or watermark". Disabling snooping makes the
# bridge flood multicast to every port — correct and reliable for a 5-node test
# segment. (Best-effort: warn but continue if /sys isn't writable.)
SNOOP_PATH="/sys/class/net/${BRIDGE_NAME}/bridge/multicast_snooping"
if echo 0 | sudo tee "${SNOOP_PATH}" >/dev/null 2>&1; then
  log "disabled IGMP snooping on ${BRIDGE_NAME} (multicast flood mode)"
else
  log "WARN: could not write ${SNOOP_PATH}; cross-node multicast may be filtered"
fi

# --- 3. Node image + 5 systemd containers -----------------------------------
log "building node image"
docker build -f docker/node.Dockerfile -t "${NODE_IMAGE}" docker/
for n in "${NODES[@]}"; do
  log "starting node ${n} (${NODE_IP[$n]})"
  # Dedicated volumes for the inner Docker's storage. Without them the in-node
  # Docker (DinD — Nomad's docker driver + the registry) puts its overlay
  # layers on the node container's OWN overlay rootfs, and the kernel rejects
  # overlay-on-overlay ("mount overlay ... invalid argument"). Both are needed:
  # /var/lib/docker (engine state) AND /var/lib/containerd (the containerd
  # image-store snapshotter, where modern Docker keeps image layers). The
  # volumes live on the host's real fs, where overlay works.
  docker volume create "kardamom-${n}-docker" >/dev/null
  docker volume create "kardamom-${n}-containerd" >/dev/null
  # Idempotent: a node left up by a previous KEEP=1 run is reused as-is.
  if docker inspect "kardamom-${n}" >/dev/null 2>&1; then
    log "node kardamom-${n} already exists; reusing"
    docker start "kardamom-${n}" >/dev/null 2>&1 || true
    continue
  fi
  docker run -d --name "kardamom-${n}" --hostname "${n}" \
    --privileged --cgroupns=host \
    -v /sys/fs/cgroup:/sys/fs/cgroup:rw \
    -v "kardamom-${n}-docker:/var/lib/docker" \
    -v "kardamom-${n}-containerd:/var/lib/containerd" \
    --tmpfs /run --tmpfs /run/lock \
    --network "${NET}" --ip "${NODE_IP[$n]}" \
    --shm-size=512m \
    "${NODE_IMAGE}" >/dev/null
done

# Wait for systemd to be ready in each (systemctl is-system-running returns
# running/degraded once up).
for n in "${NODES[@]}"; do
  log "waiting for systemd in ${n}"
  for _ in $(seq 1 30); do
    state="$(docker exec "kardamom-${n}" systemctl is-system-running 2>/dev/null || true)"
    [[ "${state}" == "running" || "${state}" == "degraded" || "${state}" == "starting" ]] && break
    sleep 1
  done
done

# --- 4. Provision with the UNMODIFIED site.yml over the docker connection ----
gen_container_inventory
log "ansible-playbook site.yml (generated container inventory: ${CONTAINER_INVENTORY})"
ANSIBLE_HOST_KEY_CHECKING=False \
  ansible-playbook -i "${CONTAINER_INVENTORY}" ansible/site.yml

# --- 5. Build thin service images from prebuilt binaries, push to r1 ---------
build_service_images
# --- 5b. Cluster image (Java Aeron-Cluster node) -----------------------------
build_cluster_image

# --- 6. Deploy the Nomad jobs + smoke ---------------------------------------
export NOMAD_ADDR="http://192.168.56.10:4646"
# Runner identity, stamped for EVERY shard (#124: chaos-case load verdicts
# show the same intermittent collapses as the load shard).
log "runner: name=${RUNNER_NAME:-local} host=$(hostname) cpus=$(nproc) loadavg=[$(cut -d' ' -f1-3 /proc/loadavg)] mem_avail_kb=$(awk '/MemAvailable/{print $2}' /proc/meminfo)"

log "deploy.sh (Nomad endpoint ${NOMAD_ADDR})"
./scripts/deploy.sh

log "smoke test (gate: single-tx must pass before load smoke runs)"
./scripts/smoke.sh

# --- 7. Sustained-load invariant gate (Rust harness: FIXED-RATE soak;
# must-deliver + drop accounting + keep-pace) then 8. chaos/resilience
# suite — env-gated stages (bodies in ci-stages.sh).
# Both stages drive the Rust kardamom-load harness (built alongside the service
# bins by the workflow, staged at target/release). Durations/rates are ENV-tunable
# so PR runs stay short and a full soak can be dialed up via the cluster-e2e.yml
# workflow_dispatch / matrix shard knobs.
#
# Funded-account budget: genesis prefunds Anvil accounts #0..#17, each its own
# contiguous nonce chain on the never-reset chain (a fresh account's first tx
# MUST be nonce 0, with no gaps). Allocation: #0 = gate smoke above; #1..#6 =
# the sustained-load harness; #7..#15 = one fresh account per chaos case (see
# chaos.sh); #16 = the ingress-churn failover re-smoke (step 7b); #17 = the
# fallback executor-churn re-smoke. Every check owns its own account, so every
# smoke tx is nonce 0 — there's no NONCE knob and no nonce-continuation.
# RUN_LOAD / RUN_CHAOS (default 1) let a CI shard run just one stage so the full
# suite can be split across runners (each shard brings up its own cluster). When
# unset both default to 1 — the local / single-runner path runs smoke + the
# default cluster chaos cases. CHAOS_CASES selects which chaos cases to run; in
# cluster mode the default set is the three Raft cases (see chaos.sh).
LOAD_BIN="${ROOT}/target/release/kardamom-load"
if [[ -x "${LOAD_BIN}" ]]; then
  if [[ "${RUN_LOAD:-1}" == "1" ]]; then
    stage_load
  else
    log "RUN_LOAD=0 — skipping sustained-load stage (chaos-only shard)"
  fi

  # chain-semantics suite (Target C) — OFF by default (RUN_SEMANTICS=0) so it
  # only runs on its own shard; see stage_semantics in ci-stages.sh.
  if [[ "${RUN_SEMANTICS:-0}" == "1" ]]; then
    stage_semantics
  fi

  if [[ "${RUN_CHAOS:-1}" == "1" ]]; then
    stage_chaos
  else
    log "RUN_CHAOS=0 — skipping chaos stage (load-only shard)"
  fi
else
  stage_fallback_load
fi

# --- 7b. Ingress active/active failover + multicast-receipts freeze guard ----
# (failover + the 2a freeze-guard rationale live with stage_ingress_churn in
# ci-stages.sh.)
stage_ingress_churn

# --- 7c. Validator sync + keep-up verdict -------------------------------------
# The validator followed everything the shard just did — bring-up, smoke, load
# and/or chaos. The full verdict (liveness, sync + keep-up, BAL verification
# with zero divergences, trie shadow-checks) lives in validator-verdict.sh,
# which also carries the divergence-log scan SHARED with the chaos suite.
log "validator verdict: sync + keep-up + BAL cross-check (no divergence)"
run_validator_verdict

log "cluster-e2e PASSED"
