#!/usr/bin/env python3
"""Render a versioned vslot-to-lane shard map as TOML.

The map is the dynamic level of sender routing (see
docs/specs/dynamic-sequencer-sizing.md, section 3.2). The ingress reads
the file through --shard-map. The sequencer job generator derives each
lane's vslot set from it.

Two modes:

  render-shard-map.py --identity <lanes>
      Map v0: lane = vslot % lanes. `lanes` must divide 256.

  render-shard-map.py --from <map.toml> --lanes <target>
      The next version, with the fewest moves. Scale-out: slots move from
      the old lanes to the new lanes until every lane holds 256 / target
      slots (the first lanes hold the remainder). Scale-in: the slots of
      the leaving lanes move to the remaining lanes, lowest load first.
      Slots that stay keep their lane, so a lane that does not gain
      slots runs through the resize without a shadow phase.

The output is `version = N` and `table = [256 lanes]`. It has no
dependency beyond Python.
"""

import argparse
import re
import sys

VSLOT_COUNT = 256
LANE_COUNT = 8


def parse_map(path: str) -> tuple[int, list[int]]:
    text = open(path).read()
    m_ver = re.search(r"^version\s*=\s*(\d+)", text, re.M)
    m_tab = re.search(r"^table\s*=\s*\[([^\]]*)\]", text, re.M | re.S)
    if not m_ver or not m_tab:
        sys.exit(f"{path}: expected `version = N` and `table = [...]`")
    table = [int(x) for x in re.findall(r"\d+", m_tab.group(1))]
    if len(table) != VSLOT_COUNT:
        sys.exit(f"{path}: table has {len(table)} entries, expected {VSLOT_COUNT}")
    if any(l >= LANE_COUNT for l in table):
        sys.exit(f"{path}: a lane is above the lane plane of {LANE_COUNT}")
    return int(m_ver.group(1)), table


def render(version: int, table: list[int]) -> str:
    rows = []
    for i in range(0, VSLOT_COUNT, 32):
        rows.append("  " + ", ".join(str(l) for l in table[i : i + 32]) + ",")
    body = "\n".join(rows)
    return (
        "# GENERATED by scripts/render-shard-map.py. Do not edit by hand.\n"
        "# The vslot-to-lane map (docs/specs/dynamic-sequencer-sizing.md, 3.2).\n"
        "# Index = vslot (keccak256(sender)[..8] % 256). Value = tx_data lane.\n"
        f"version = {version}\n"
        f"table = [\n{body}\n]\n"
    )


def identity(lanes: int) -> list[int]:
    if lanes < 1 or lanes > LANE_COUNT or VSLOT_COUNT % lanes != 0:
        sys.exit(f"--identity needs a lane count in {{1, 2, 4, 8}}, got {lanes}")
    return [v % lanes for v in range(VSLOT_COUNT)]


def next_map(table: list[int], target: int) -> list[int]:
    if target < 1 or target > LANE_COUNT:
        sys.exit(f"--lanes must be in 1..={LANE_COUNT}, got {target}")
    current = max(table) + 1
    out = list(table)
    if target == current:
        return out
    # The target load per lane: the first `remainder` lanes hold one more.
    base, rem = divmod(VSLOT_COUNT, target)
    want = [base + (1 if lane < rem else 0) for lane in range(target)]
    load = [0] * LANE_COUNT
    for l in out:
        load[l] += 1
    # Move a slot from an over-full or leaving lane to the most under-full
    # lane. Walk the slots in order, so the result is deterministic.
    def most_under_full() -> int:
        best, best_gap = -1, 0
        for lane in range(target):
            gap = want[lane] - load[lane]
            if gap > best_gap:
                best, best_gap = lane, gap
        return best
    for v in range(VSLOT_COUNT):
        lane = out[v]
        leaving = lane >= target
        over = not leaving and load[lane] > want[lane]
        if not (leaving or over):
            continue
        dest = most_under_full()
        if dest < 0:
            sys.exit("internal: no under-full lane while slots remain to move")
        out[v] = dest
        load[lane] -= 1
        load[dest] += 1
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--identity", type=int, help="render map v0 over this many lanes")
    ap.add_argument("--from", dest="src", help="the current map file")
    ap.add_argument("--lanes", type=int, help="the target lane count (with --from)")
    ap.add_argument("--version", type=int, help="override the output version")
    a = ap.parse_args()
    if a.identity is not None:
        version = 0 if a.version is None else a.version
        sys.stdout.write(render(version, identity(a.identity)))
        return
    if a.src and a.lanes is not None:
        version, table = parse_map(a.src)
        out = next_map(table, a.lanes)
        new_version = version + 1 if a.version is None else a.version
        sys.stdout.write(render(new_version, out))
        return
    ap.error("use --identity <lanes>, or --from <map> --lanes <target>")


if __name__ == "__main__":
    main()
