#!/usr/bin/env python3
"""Render nomad/sequencer.nomad.hcl from the shard map and group_vars.

One job group per active lane, `count = 2` (the racing replicas) with
`distinct_hosts`. Each group passes an explicit `--lane` and `--vslots`.
The ports form a lane: metrics `9001 + 10 * lane`, cluster egress
`cluster_egress_port + 10 * lane`. Two lanes can share a node without a
port clash. See docs/specs/dynamic-sequencer-sizing.md, section 3.8.

Modes:

  render-sequencer-job.py [--map config/shard-map.toml]
      The steady state: every lane of the map, final config.

  render-sequencer-job.py --map <next.toml> --from <current.toml>
      The overlap of a resize (section 3.5, step 1). A lane whose set is
      unchanged keeps its exact arguments, so Nomad does not restart it.
      A lane that gains slots reads the old lanes of those slots too
      (--extra-lanes) and starts them in shadow mode (--shadow-vslots).
      A lane that only loses slots keeps its old set until the steady
      render, so it serves through the overlap.

The checked-in job file must equal the steady render for the checked-in
map. scripts/check-contract.py checks that. scripts/scale-sequencers.sh
drives the two renders of a resize.
"""

import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
CLUSTER = os.path.dirname(HERE)
GROUP_VARS = os.path.join(CLUSTER, "ansible", "group_vars", "all.yml")
DEFAULT_MAP = os.path.join(CLUSTER, "config", "shard-map.toml")

VSLOT_COUNT = 256
METRICS_BASE = 9001
PORT_LANE_STEP = 10
MDC_PORT_BASE = 40340


def scalar(text: str, key: str) -> str:
    m = re.search(rf"^{re.escape(key)}:\s*([^#\n]+)", text, re.M)
    if not m:
        sys.exit(f"group_vars/all.yml: missing key '{key}'")
    return m.group(1).strip().strip('"').strip("'")


def port(text: str, key: str) -> int:
    m = re.search(rf"^\s{{2}}{re.escape(key)}:\s*(\d+)", text, re.M)
    if not m:
        sys.exit(f"group_vars/all.yml: missing ports.{key}")
    return int(m.group(1))


def node_class(text: str, name: str) -> tuple[int, int]:
    m = re.search(rf"^\s{{2}}{name}:\s*\{{[^}}]*?\bcount:\s*(\d+)[^}}]*?\bip_start:\s*(\d+)", text, re.M)
    if not m:
        sys.exit(f"group_vars/all.yml: missing node_classes.{name}")
    return int(m.group(1)), int(m.group(2))


def parse_map(path: str) -> tuple[int, list[int]]:
    text = open(path).read()
    m_ver = re.search(r"^version\s*=\s*(\d+)", text, re.M)
    m_tab = re.search(r"^table\s*=\s*\[([^\]]*)\]", text, re.M | re.S)
    if not m_ver or not m_tab:
        sys.exit(f"{path}: expected `version = N` and `table = [...]`")
    table = [int(x) for x in re.findall(r"\d+", m_tab.group(1))]
    if len(table) != VSLOT_COUNT:
        sys.exit(f"{path}: table has {len(table)} entries, expected {VSLOT_COUNT}")
    return int(m_ver.group(1)), table


def ranges(slots: list[int]) -> str:
    """The text form of a vslot set: `0-7,16,32-47`."""
    out: list[str] = []
    run: tuple[int, int] | None = None
    for v in sorted(slots):
        if run and run[1] + 1 == v:
            run = (run[0], v)
            continue
        if run:
            out.append(f"{run[0]}-{run[1]}" if run[0] != run[1] else str(run[0]))
        run = (v, v)
    if run:
        out.append(f"{run[0]}-{run[1]}" if run[0] != run[1] else str(run[0]))
    return ",".join(out)


def lane_sets(table: list[int]) -> dict[int, list[int]]:
    sets: dict[int, list[int]] = {}
    for v, lane in enumerate(table):
        sets.setdefault(lane, []).append(v)
    return sets


HEADER = """\
# GENERATED by scripts/render-sequencer-job.py. Do not edit by hand.
#
# kardamom-sequencer: one job group per active tx_data lane, with 2
# racing replicas per lane (count = 2, distinct_hosts). Both replicas of
# a lane subscribe to the same per-lane tx_data multicast stream, and
# both offer refs to the Aeron Cluster, which dedups by canonical_id
# first-seen. So a replica crash costs nothing; its twin never stopped.
# See docs/agents/replicated-sequencer-shards-spec.md.
#
# Each group passes an explicit --lane and --vslots, derived from
# config/shard-map.toml (docs/specs/dynamic-sequencer-sizing.md, 3.2).
# The ports form a lane: metrics 9001 + 10 * lane, cluster egress
# {egress_base} + 10 * lane. Two lanes share a node without a clash.
# Placement is by Nomad, not by node meta.
#
# Note for consumers: both replicas of a lane process the same tx
# stream, so per-lane tx totals exist once per replica. Aggregate
# stream-derived counters with `max by (partition)`, never `sum`.
#
# This shares the node's Aeron media driver, through the bind-mounted
# tmpfs aeron.dir.

# Digest-pinned image. ansible/deploy.yml passes the repo:tag@sha256:...
# reference captured at push time (deploy/cluster/images.digests). Both
# replicas of every lane run the same pinned bytes. The empty default
# falls back to the mutable :dev tag in the task configs. That fallback
# is a dev affordance for manual `nomad job run` during debugging, not a
# production path.
variable "image_ref" {{
  type        = string
  description = "Digest-pinned image reference (repo:tag@sha256:...) from the deploy's push manifest. Empty = mutable :dev tag fallback (dev-only)."
  default     = ""
}}

job "sequencer" {{
  datacenters = ["dc1"]
  type        = "service"

  # Sequencer-role nodes only.
  constraint {{
    attribute = "${{meta.role}}"
    value     = "sequencer"
  }}
"""

GROUP = """
  group "seq-{lane}" {{
    # The two racing replicas of lane {lane}, on distinct nodes.
    count = 2
    constraint {{
      operator = "distinct_hosts"
      value    = "true"
    }}

    # Resilience (chaos tests): restart a crashed task on the same
    # node, and reschedule onto a healthy node on node loss. With
    # distinct_hosts, a lost replica reschedules only when a free node
    # returns. Its lane stays live the whole time, through the twin.
    restart {{
      attempts = 3
      interval = "1m"
      delay    = "5s"
      mode     = "delay"
    }}

    reschedule {{
      delay          = "10s"
      delay_function = "exponential"
      max_delay      = "1m"
      unlimited      = true
    }}

    # One replica at a time, so a config change (a resize step) never
    # takes both replicas of a lane down together.
    update {{
      max_parallel     = 1
      health_check     = "task_states"
      min_healthy_time = "10s"
      healthy_deadline = "2m"
      auto_revert      = false
    }}

    network {{
      mode = "host"
    }}

    task "sequencer-{lane}" {{
      driver = "docker"

      config {{
        image = var.image_ref != "" ? var.image_ref : "{image}"
        # force_pull stays on for both paths; see the ingress job's
        # comment. The :dev fallback needs it. On the pinned path, the
        # 1.9.5 driver pulls the tag but resolves the image by digest,
        # so the pin holds.
        force_pull = true
        # Read-only rootfs. The sequencer writes only to the
        # bind-mounted aeron directory, plus Nomad's alloc, local, and
        # secrets mounts. cluster-e2e validates this.
        readonly_rootfs = true
        network_mode    = "host"
        volumes = [
          "/opt/kardamom/aeron-mount:/opt/kardamom/aeron-mount",
        ]
        args = [
          "--config", "/local/sequencer.toml",
          "--log-config", "/local/channels.toml",
          "--aeron-dir", "/opt/kardamom/aeron-mount/dir",
          # The active lane count and this lane. partition_index labels
          # the metrics; the vslot set below is the routing truth.
          "--partition-count", "{lanes}",
          "--partition-index", "{lane}",
          "--sequencer-id", "{lane}",
          "--lane", "{lane}",
          "--vslots", "{vslots}",{resize_args}
          # The transaction lifetime (tx_ttl_ms in group_vars/all.yml).
          "--tx-ttl-ms", "{tx_ttl_ms}",
          # The executor nonce query endpoints (node_classes.executor and
          # ports.executor_nonce_query in group_vars/all.yml).
          "--executor-query-endpoints", "{query_endpoints}",
          # This node's cluster-egress (response) endpoint, on the lane's
          # port. The node IP differs per replica, so it is injected here.
          "--cluster-egress-endpoint", "${{meta.node_ip}}:{egress_port}",
        ]
      }}

      env {{
        # Bind 0.0.0.0 so the process is scrapable off-node, on the
        # lane's metrics port. The host id names the node and the lane.
        KARDAMOM_METRICS_ADDR = "0.0.0.0:{metrics_port}"
        KARDAMOM_HOST_ID      = "node${{meta.node_index}}-seq-{lane}"
        # The UDP ports the discovered tx_errors publication binds, on
        # the lane's range, so two lanes can share a node.
        KARDAMOM_MDC_PORTS    = "{mdc_ports}"
      }}

      # Cluster LogConfig (Aeron streams and discovery), read through
      # --log-config.
      template {{
        destination = "local/channels.toml"
        data        = file("config/channels.toml.tpl")
      }}

      # This comes from one source, config/sequencer.toml.tpl. The
      # partition and lane fields in that file are placeholders,
      # overridden by the CLI flags above.
      template {{
        destination = "local/sequencer.toml"
        data        = file("config/sequencer.toml.tpl")
      }}

      resources {{
        cpu    = 750
        memory = 512
      }}
    }}
  }}
"""


def render(gv: str, target: list[int], current: list[int] | None) -> str:
    registry = f"{scalar(gv, 'registry_host')}:{scalar(gv, 'registry_port')}"
    image = f"{registry}/kardamom-sequencer:{scalar(gv, 'image_tag')}"
    tx_ttl_ms = scalar(gv, "tx_ttl_ms")
    egress_base = int(scalar(gv, "cluster_egress_port"))
    ip_prefix = scalar(gv, "ip_prefix")
    query_port = port(gv, "executor_nonce_query")
    exec_count, exec_start = node_class(gv, "executor")
    query_endpoints = ",".join(
        f"http://{ip_prefix}.{exec_start + i}:{query_port}" for i in range(exec_count)
    )
    target_sets = lane_sets(target)
    lanes = max(target) + 1
    current_sets = lane_sets(current) if current is not None else None
    current_lanes = max(current) + 1 if current is not None else lanes

    out = [HEADER.format(egress_base=egress_base)]
    groups = sorted(set(target_sets) | (set(current_sets) if current_sets else set()))
    for lane in groups:
        resize_args = ""
        # The lane count each group reports. An untouched group keeps the
        # current count, so its arguments stay byte-identical and Nomad
        # does not restart it during the overlap.
        lanes_arg = lanes
        if current_sets is None:
            vslots = target_sets[lane]
        elif lane not in target_sets:
            # A leaving lane serves its old set through the overlap. The
            # steady render drops the group, and Nomad stops it.
            vslots = current_sets[lane]
            lanes_arg = current_lanes
        else:
            new = target_sets[lane]
            old = current_sets.get(lane, [])
            incoming = sorted(set(new) - set(old))
            if not incoming:
                # Unchanged, or only losing slots: keep serving the old
                # set. The arguments stay byte-identical, so Nomad does
                # not restart the group.
                vslots = old
                lanes_arg = current_lanes
            else:
                vslots = new
                old_lanes = sorted({current[v] for v in incoming})
                resize_args = (
                    "\n          # The overlap of a resize: read the old lanes of the"
                    "\n          # incoming vslots, and start those vslots in shadow mode."
                    f'\n          "--extra-lanes", "{",".join(str(l) for l in old_lanes)}",'
                    f'\n          "--shadow-vslots", "{ranges(incoming)}",'
                )
        out.append(
            GROUP.format(
                lane=lane,
                lanes=lanes_arg,
                image=image,
                vslots=ranges(vslots),
                resize_args=resize_args,
                tx_ttl_ms=tx_ttl_ms,
                query_endpoints=query_endpoints,
                egress_port=egress_base + PORT_LANE_STEP * lane,
                metrics_port=METRICS_BASE + PORT_LANE_STEP * lane,
                mdc_ports=(
                    f"{MDC_PORT_BASE + PORT_LANE_STEP * lane}-"
                    f"{MDC_PORT_BASE + PORT_LANE_STEP * lane + PORT_LANE_STEP - 1}"
                ),
            )
        )
    out.append("}\n")
    return "".join(out)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--map", default=DEFAULT_MAP, help="the target map (default: config/shard-map.toml)")
    ap.add_argument("--from", dest="src", help="the current map, for the overlap render")
    ap.add_argument("--group-vars", default=GROUP_VARS)
    a = ap.parse_args()
    gv = open(a.group_vars).read()
    _, target = parse_map(a.map)
    current = parse_map(a.src)[1] if a.src else None
    sys.stdout.write(render(gv, target, current))


if __name__ == "__main__":
    main()
