[package]
name = "kardamom-node"
version.workspace = true
edition.workspace = true
build = "build.rs"

[dependencies]
kardamom-types.workspace = true
revm.workspace = true
alloy-primitives.workspace = true
alloy-consensus.workspace = true
alloy-rpc-types-eth.workspace = true
alloy-rlp.workspace = true
alloy-network.workspace = true
alloy-eips.workspace = true
op-alloy-consensus.workspace = true
jsonrpsee.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
anyhow.workspace = true
tracing.workspace = true
metrics.workspace = true
async-trait = "0.1"

[dev-dependencies]
alloy-signer-local.workspace = true
metrics-exporter-prometheus.workspace = true
alloy-provider.workspace = true
alloy-contract.workspace = true
alloy-sol-types.workspace = true
alloy-node-bindings.workspace = true
kardamom-deployer = { path = "../deployer" }
